# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include:
  - assets

title: "Salik Nawaz"
tagline: "Photonic Specialist"
description: "Portfolio, projects, and contact."
author:
  name: "Salik Nawaz"
  title: "Photonic Specialist"
  email: "saliknawaz30@gmail.com"
  mobile: "+49(0)15901376676"
  location: "Paderborn, Germany"
  #avatar: "/assets/images/profile.jpg"
  photo: "/assets/images/profile03.jpg" 
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/salik-nawaz-318699156/"
    - label: "GitHub"
      url: "https://github.com/YOURUSERNAME"
    - label: "CV (English)"
      url: "/assets/cv/salik_nawaz_cv_en.pdf"
    - label: "CV (Deutsch)"
      url: "/assets/cv/salik_nawaz_cv_de.pdf"


#title: "Salik Nawaz"
#tagline: "Photonic Specialist"
#description: "Portfolio, projects, and contact."
#url: "https://YOURUSERNAME.github.io"  # change after you push
#author:
#  name: "Salik Nawaz"
#  email: "saliknawaz30@gmail.com"
#  mobile: "+49(0)15901376676"  # optional, remove if not needed
#  location: "Paderborn, Germany"  # optional, remove if not needed
#  links:
#    - label: LinkedIn
#      url: "https://www.linkedin.com/in/salik-nawaz-318699156/"
#    - label: GitHub
#      url: "https://github.com/YOURUSERNAME"
#    - label: CV (English)
#      url: "https://link-to-your-english-cv.pdf"
#    - label: CV (Deutsch)
#      url: "https://link-to-your-german-cv.pdf"

theme: minima   # simple, clean default
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional analytics (add your ID if you have one)
# google_analytics: "G-XXXXXXXXXX"


#title: Your awesome title
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
